apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: og-img-preview
  name: og-img-preview
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: og-img-preview
  strategy: { }
  template:
    metadata:
      labels:
        service: og-img-preview
    spec:
      containers:
        - image: maksim1111/og-img-preview:latest
          name: og-img-preview
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 1
            initialDelaySeconds: 30
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: og-img-preview
  name: og-img-preview
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    service: og-img-preview
---
